#!/bin/bash

assert-equal () {
    diff -q <("${ANGELIX_RUN:-eval}" $1) <(echo "$2") > /dev/null
}

[ $# -ne 2 ] && echo "Usage: $0 box test" && exit 1

oracle_dir=$(dirname $0)
box=$1
test=$2

input=$(<$oracle_dir/tests/$box/$test.in)
output=$(cat $oracle_dir/tests/$box/$test.out | cut -d '>' -f 2 | sed 's/[^0-9]\+//g')

assert-equal "./median $input" "$output"
