#!/bin/bash

assert-equal () {
    diff -q <("${ANGELIX_RUN:-eval}" $1) <(echo "$2") > /dev/null
}

[ $# -ne 2 ] && echo "Usage: $0 box test" && exit 1

tests_dir=$(dirname $0)/../tests
box=$1
test=$2

input=$(<$tests_dir/$box/$test.in)
output=$(cat $tests_dir/$box/$test.out | cut -d '>' -f 2 | sed 's/[^0-9]\+//g')

assert-equal "./median $input" "$output"
