#!/bin/bash

[ $# -ne 1 ] && echo "Usage: $0 buggy" && exit 1

buggy=$1
buggy_bn=$(basename $buggy)
prog=${buggy_bn%.c}
src_dir=$(dirname $buggy)/src

mkdir -p $src_dir

cat > $src_dir/Makefile <<EOF
CC=gcc
CFLAGS=-I.

all:
	\$(CC) \$(CFLAGS) -c $prog.c -o $prog.o
	\$(CC) $prog.o -o $prog
EOF

sed -f $(dirname $0)/instrument_buggy.sed $buggy > $src_dir/$buggy_bn
