#!/bin/bash

assert-equal () {
    diff -q <("${ANGELIX_RUN:-eval}" $1) <(echo "$2") > /dev/null
}

[ $# -ne 2 ] && echo "Usage: $0 box test" && exit 1

tests_dir=$(dirname $0)/../tests
box=$1
test=$2

input=$(<$tests_dir/$box/$test.in)
output=$(sed -n '/^[-0-9]\+$/p' $tests_dir/$box/$test.out)

assert-equal "./digits $input" "$output"
